backend/config/routes.rb
Rails.application.routes.draw do
  resources :chats
  devise_for :users, controllers: { sessions: 'users/sessions' }
  root to: 'posts#index'

  resources :secrets
  resources :posts
  resources :users

  get '/settings/one', to: 'settings#one'
  get '/settings/two', to: 'settings#two'
  get '/slow_request', to: 'settings#slow_request'
end

backend/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExampleApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <header>
      <div class="navbar navbar-dark bg-dark box-shadow">
        <div class="container d-flex justify-content-between">
          <a href="#" class="navbar-brand d-flex align-items-center">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path><circle cx="12" cy="13" r="4"></circle></svg>
            <strong>Example App</strong>
          </a>

          <div style="color: white;">
            <% if user_signed_in? %>
              Logged in as: <%= current_user.name %>

              <%= link_to destroy_user_session_path, method: :delete do %>
                <button class="btn btn-outline-light" type="submit">Logout</button>
              <% end %>
            <% else %>
              <%= link_to new_user_session_path do %>
                <button class="btn btn-outline-light" type="submit">Login</button>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </header>

    <main role="main">
      <div class="container" style="margin-top: 10px;">
        <% if notice.present? %>

          <div class="alert alert-success" role="alert">
            <%= notice %>
          </div>
        <% end %>

        <% if alert.present? %>
          <div class="alert alert-danger" role="alert">
            <%= alert %>
          </div>
        <% end %>

        <ul class="nav nav-tabs">
          <li class="nav-item">
            <%= link_to posts_path, class: "nav-link #{class_for_nav('/posts')}" do %>
              Posts
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to secrets_path, class: "nav-link #{class_for_nav('/secrets')}" do %>
              Secrets
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to chats_path, class: "nav-link #{class_for_nav('/chats')}" do %>
              Chat
            <% end %>
          </li>
        </ul>

      </div>
      <div class="container">
        <%= yield %>
      </div>
    </main>
  </body>
</html>